program: cilrs_train.py
project: cilrs_training
method: grid
metric:
  name : val/loss_epoch
  goal : minimize

parameters:
  learning_rate:
    values: [0.0002]
  weight_decay:
    values: [0.001, 0.0001, 0.00001]
  dropout_p:
    values: [0.5, 0.1]
  cond_module:
    values: ['command_input']
  # speed_coeff:
  #   values: [1.0, 0.5]
  # brake_coeff:
  #   values: [1.0, 1.5, 0.5]
  # steer_coeff:
  #   values: [1.0, 1.5, 0.5]
  

